/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:57:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.stages.model.*;
import com.stages.dao.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class admin_002dcandidatures_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.stages.model");
    _jspx_imports_packages.add("com.stages.dao");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String admin = (String) session.getAttribute("admin");
    if (admin == null) {
        response.sendRedirect("login");
        return;
    }
    
    Map<Integer, List<Candidature>> candidaturesGrouped = (Map<Integer, List<Candidature>>) request.getAttribute("candidaturesGrouped");
    Map<Integer, String> studentNames = (Map<Integer, String>) request.getAttribute("studentNames");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    
    // Initialize DAOs for quiz data
    QuizDAO quizDAO = new QuizDAO();
    QuizAttemptDAO quizAttemptDAO = new QuizAttemptDAO();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Toutes les Candidatures - StageConnect</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/navbar-admin.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>Toutes les Candidatures</h1>\n");
      out.write("            <p>Voir toutes les candidatures</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Status Filter -->\n");
      out.write("        <div class=\"card filter-card\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                <form action=\"admin-candidatures\" method=\"get\" class=\"filter-form\">\n");
      out.write("                    <div class=\"filter-row\">\n");
      out.write("                        <label for=\"statut\">Filtrer par statut :</label>\n");
      out.write("                        <select id=\"statut\" name=\"statut\" onchange=\"this.form.submit()\">\n");
      out.write("                            <option value=\"all\" ");
      out.print( "all".equals(request.getAttribute("selectedStatut")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                Tous les statuts\n");
      out.write("                            </option>\n");
      out.write("                            <option value=\"En attente\" ");
      out.print( "En attente".equals(request.getAttribute("selectedStatut")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                En attente\n");
      out.write("                            </option>\n");
      out.write("                            <option value=\"Acceptée\" ");
      out.print( "Acceptée".equals(request.getAttribute("selectedStatut")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                Acceptée\n");
      out.write("                            </option>\n");
      out.write("                            <option value=\"Refusée\" ");
      out.print( "Refusée".equals(request.getAttribute("selectedStatut")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                Refusée\n");
      out.write("                            </option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Grouped Applications -->\n");
      out.write("        ");
 if (candidaturesGrouped != null && !candidaturesGrouped.isEmpty()) { 
      out.write("\n");
      out.write("            ");
 for (Map.Entry<Integer, List<Candidature>> entry : candidaturesGrouped.entrySet()) { 
      out.write("\n");
      out.write("                <div class=\"card mb-lg\">\n");
      out.write("                    <div class=\"card-header\">\n");
      out.write("                        <h3>");
      out.print( studentNames.get(entry.getKey()) );
      out.write("</h3>\n");
      out.write("                        <span class=\"text-muted\">Nombre de candidatures: ");
      out.print( entry.getValue().size() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        \n");
      out.write("                        <div class=\"table-responsive\">\n");
      out.write("                            <table class=\"admin-table\">\n");
      out.write("                                <thead>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Offre</th>\n");
      out.write("                                        <th>Entreprise</th>\n");
      out.write("                                        <th>Date</th>\n");
      out.write("                                        <th>Statut</th>\n");
      out.write("                                        <th>Actions</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody>\n");
      out.write("                                    ");
 for (Candidature c : entry.getValue()) { 
      out.write("\n");
      out.write("                                        <tr>\n");
      out.write("                                            <td>");
      out.print( c.getOffreTitre() );
      out.write("</td>\n");
      out.write("                                            <td>");
      out.print( c.getEntrepriseName() );
      out.write("</td>\n");
      out.write("                                            <td>");
      out.print( sdf.format(c.getDateCandidature()) );
      out.write("</td>\n");
      out.write("                                            <td>\n");
      out.write("                                                <span class=\"status-badge status-");
      out.print( c.getStatut().toLowerCase().replace(" ", "-").replace("é", "e") );
      out.write("\">\n");
      out.write("                                                    ");
      out.print( c.getStatut() );
      out.write("\n");
      out.write("                                                </span>\n");
      out.write("                                            </td>\n");
      out.write("                                            <td class=\"actions-cell\">\n");
      out.write("                                                <button onclick=\"viewDetails(");
      out.print( c.getId() );
      out.write(")\" class=\"btn btn-sm btn-secondary\">\n");
      out.write("                                                    Voir Details\n");
      out.write("                                                </button>\n");
      out.write("                                            </td>\n");
      out.write("                                        </tr>\n");
      out.write("                                        \n");
      out.write("                                        <!-- Hidden details row -->\n");
      out.write("                                        <tr id=\"details-");
      out.print( c.getId() );
      out.write("\" class=\"details-row\">\n");
      out.write("                                            <td colspan=\"5\">\n");
      out.write("                                                <div class=\"application-details-admin\">\n");
      out.write("                                                    <h4>Détails de la candidature</h4>\n");
      out.write("                                                    \n");
      out.write("                                                    ");
 if (c.getQuizAttemptId() != null && c.getQuizAttemptId() > 0) { 
                                                        QuizAttempt attempt = quizAttemptDAO.getAttemptById(c.getQuizAttemptId());
                                                        if (attempt != null) {
                                                            List<QuizResponse> responses = quizAttemptDAO.getResponsesByAttemptId(c.getQuizAttemptId());
                                                            if (responses != null && !responses.isEmpty()) {
                                                    
      out.write("\n");
      out.write("                                                        <div class=\"detail-section quiz-result-section\">\n");
      out.write("                                                            <strong>Résultat du Quiz :</strong>\n");
      out.write("                                                            <div class=\"quiz-score-display mb-md\">\n");
      out.write("                                                                <span class=\"score-badge ");
      out.print( attempt.getScore() >= 75 ? "badge-success" : "badge-danger" );
      out.write("\">\n");
      out.write("                                                                    ");
      out.print( String.format("%.1f", attempt.getScore()) );
      out.write("%\n");
      out.write("                                                                </span>\n");
      out.write("                                                                <span class=\"text-muted\">\n");
      out.write("                                                                    (");
      out.print( attempt.getEarnedPoints() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( attempt.getTotalPoints() );
      out.write(" points)\n");
      out.write("                                                                </span>\n");
      out.write("                                                            </div>\n");
      out.write("                                                            \n");
      out.write("                                                            <div class=\"quiz-answers-inline\">\n");
      out.write("                                                                <h5>Réponses du candidat:</h5>\n");
      out.write("                                                                ");
 for (int i = 0; i < responses.size(); i++) {
                                                                    QuizResponse resp = responses.get(i);
                                                                    if (resp != null && resp.getQuestionId() > 0) {
                                                                        QuizQuestion question = quizDAO.getQuestionById(resp.getQuestionId());
                                                                        if (question != null && resp.getSelectedAnswer() != null) {
                                                                            String selectedAnswer = resp.getSelectedAnswer();
                                                                            String correctAnswer = question.getCorrectAnswer() != null ? question.getCorrectAnswer() : "";
                                                                
      out.write("\n");
      out.write("                                                                    <div class=\"quiz-answer-item ");
      out.print( resp.isCorrect() ? "correct" : "incorrect" );
      out.write("\">\n");
      out.write("                                                                        <p class=\"question-text\"><strong>Q");
      out.print( (i + 1) );
      out.write(":</strong> ");
      out.print( question.getQuestionText() != null ? question.getQuestionText() : "" );
      out.write("</p>\n");
      out.write("                                                                        <p class=\"student-answer\">\n");
      out.write("                                                                            <strong>Réponse:</strong> \n");
      out.write("                                                                            <span class=\"");
      out.print( resp.isCorrect() ? "text-success" : "text-danger" );
      out.write("\">\n");
      out.write("                                                                                ");
      out.print( selectedAnswer.toUpperCase() );
      out.write(')');
      out.write(' ');
      out.print( question.getOptionByLetter(selectedAnswer) );
      out.write("\n");
      out.write("                                                                            </span>\n");
      out.write("                                                                        </p>\n");
      out.write("                                                                        ");
 if (!resp.isCorrect() && !correctAnswer.isEmpty()) { 
      out.write("\n");
      out.write("                                                                            <p class=\"correct-answer\">\n");
      out.write("                                                                                <strong>Correct:</strong> \n");
      out.write("                                                                                <span class=\"text-success\">\n");
      out.write("                                                                                    ");
      out.print( correctAnswer.toUpperCase() );
      out.write(')');
      out.write(' ');
      out.print( question.getOptionByLetter(correctAnswer) );
      out.write("\n");
      out.write("                                                                                </span>\n");
      out.write("                                                                            </p>\n");
      out.write("                                                                        ");
 } 
      out.write("\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                ");
 
                                                                        }
                                                                    }
                                                                } 
      out.write("\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    ");
 
                                                            }
                                                        }
                                                    } 
      out.write("\n");
      out.write("                                                    \n");
      out.write("                                                    ");
 if (c.getLettreMotivation() != null && !c.getLettreMotivation().isEmpty()) { 
      out.write("\n");
      out.write("                                                        <div class=\"detail-section\">\n");
      out.write("                                                            <strong>Lettre de motivation :</strong>\n");
      out.write("                                                            <p>");
      out.print( c.getLettreMotivation() );
      out.write("</p>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    ");
 } 
      out.write("\n");
      out.write("                                                    ");
 if (c.getCommentaireAdmin() != null && !c.getCommentaireAdmin().isEmpty()) { 
      out.write("\n");
      out.write("                                                        <div class=\"detail-section\">\n");
      out.write("                                                            <strong>Commentaire :</strong>\n");
      out.write("                                                            <p>");
      out.print( c.getCommentaireAdmin() );
      out.write("</p>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    ");
 } 
      out.write("\n");
      out.write("                                                    ");
 if (c.getDateReponse() != null) { 
      out.write("\n");
      out.write("                                                        <div class=\"detail-section\">\n");
      out.write("                                                            <strong>Date de réponse :</strong>\n");
      out.write("                                                            <p>");
      out.print( sdf.format(c.getDateReponse()) );
      out.write("</p>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    ");
 } 
      out.write("\n");
      out.write("                                                </div>\n");
      out.write("                                            </td>\n");
      out.write("                                        </tr>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <p class=\"text-center text-muted\">Aucune candidature à afficher.</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function viewDetails(id) {\n");
      out.write("            const row = document.getElementById('details-' + id);\n");
      out.write("            if (row.style.display === 'none') {\n");
      out.write("                row.style.display = 'table-row';\n");
      out.write("            } else {\n");
      out.write("                row.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
