/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:57:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.stages.model.*;
import com.stages.dao.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class admin_002doffres_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.stages.model");
    _jspx_imports_packages.add("com.stages.dao");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String admin = (String) session.getAttribute("admin");
    if (admin == null) {
        response.sendRedirect("login");
        return;
    }
    
    List<Entreprise> entreprises = (List<Entreprise>) request.getAttribute("entreprises");
    Entreprise selectedEntreprise = (Entreprise) request.getAttribute("selectedEntreprise");
    List<OffreStage> offres = (List<OffreStage>) request.getAttribute("offres");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    // Initialize DAO for quiz data
    QuizDAO quizDAO = new QuizDAO();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Offres des Entreprises - StageConnect</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/navbar-admin.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>Offres des Entreprises</h1>\n");
      out.write("            <p>Voir les entreprises et leurs offres de stage</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");
 if (selectedEntreprise == null) { 
      out.write("\n");
      out.write("            <!-- List of all enterprises -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("            <div class=\"card-header\">\n");
      out.write("                <h2>Entreprises</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                    ");
 if (entreprises != null && !entreprises.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"offers-grid\">\n");
      out.write("                            ");
 for (Entreprise ent : entreprises) { 
      out.write("\n");
      out.write("                                <div class=\"entreprise-card\">\n");
      out.write("                                    <div class=\"entreprise-header\">\n");
      out.write("                                        <h3>");
      out.print( ent.getNom() );
      out.write("</h3>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"entreprise-details\">\n");
      out.write("                                        ");
 if (ent.getSecteur() != null) { 
      out.write("\n");
      out.write("                                            <div class=\"detail-item\">\n");
      out.write("                                                <strong>Secteur:</strong> ");
      out.print( ent.getSecteur() );
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                        ");
 if (ent.getZoneGeographique() != null) { 
      out.write("\n");
      out.write("                                            <div class=\"detail-item\">\n");
      out.write("                                                <strong>Zone:</strong> ");
      out.print( ent.getZoneGeographique() );
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                        ");
 if (ent.getEmail() != null) { 
      out.write("\n");
      out.write("                                            <div class=\"detail-item text-muted\">\n");
      out.write("                                                ");
      out.print( ent.getEmail() );
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"entreprise-actions\">\n");
      out.write("                                        <a href=\"admin-offres?entrepriseId=");
      out.print( ent.getId() );
      out.write("\" class=\"btn btn-primary btn-block\">\n");
      out.write("                                            Voir les offres\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <p class=\"text-center text-muted\">Aucune entreprise inscrite.</p>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <!-- Enterprise details and offers -->\n");
      out.write("            <div class=\"mb-lg\">\n");
      out.write("                <a href=\"admin-offres\" class=\"btn btn-secondary\">← Retour a la liste des entreprises</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card mb-lg\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h2>");
      out.print( selectedEntreprise.getNom() );
      out.write("</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"entreprise-info-grid\">\n");
      out.write("                        ");
 if (selectedEntreprise.getEmail() != null) { 
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <strong>Email:</strong><br>\n");
      out.write("                                ");
      out.print( selectedEntreprise.getEmail() );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        ");
 if (selectedEntreprise.getTelephone() != null) { 
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <strong>Téléphone:</strong><br>\n");
      out.write("                                ");
      out.print( selectedEntreprise.getTelephone() );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        ");
 if (selectedEntreprise.getSecteur() != null) { 
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <strong>Secteur:</strong><br>\n");
      out.write("                                ");
      out.print( selectedEntreprise.getSecteur() );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        ");
 if (selectedEntreprise.getZoneGeographique() != null) { 
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <strong>Zone géographique:</strong><br>\n");
      out.write("                                ");
      out.print( selectedEntreprise.getZoneGeographique() );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        ");
 if (selectedEntreprise.getAdresse() != null) { 
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <strong>Adresse:</strong><br>\n");
      out.write("                                ");
      out.print( selectedEntreprise.getAdresse() );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        ");
 if (selectedEntreprise.getSiteWeb() != null) { 
      out.write("\n");
      out.write("                            <div>\n");
      out.write("                                <strong>Site web:</strong><br>\n");
      out.write("                                <a href=\"");
      out.print( selectedEntreprise.getSiteWeb() );
      out.write("\" target=\"_blank\">");
      out.print( selectedEntreprise.getSiteWeb() );
      out.write("</a>\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    ");
 if (selectedEntreprise.getDescription() != null && !selectedEntreprise.getDescription().isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"mt-xl\" style=\"padding-top: var(--spacing-xl); border-top: 1px solid var(--color-border-main);\">\n");
      out.write("                            <strong>Description:</strong>\n");
      out.write("                            <p class=\"text-secondary\">");
      out.print( selectedEntreprise.getDescription() );
      out.write("</p>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h3>Offres de stage</h3>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    ");
 if (offres != null && !offres.isEmpty()) { 
      out.write("\n");
      out.write("                        <div class=\"offers-list\">\n");
      out.write("                            ");
 for (OffreStage offre : offres) { 
      out.write("\n");
      out.write("                                <div class=\"offer-card mb-lg\">\n");
      out.write("                                    <div class=\"offer-header\">\n");
      out.write("                                        <h4>");
      out.print( offre.getTitre() );
      out.write("</h4>\n");
      out.write("                                        ");
 if (offre.hasQuiz()) { 
      out.write("\n");
      out.write("                                            <span class=\"badge badge-warning\">Quiz Requis</span>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"entreprise-info-grid\">\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Spécialité:</strong> ");
      out.print( offre.getSpecialite() );
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Type:</strong> ");
      out.print( offre.getTypeStage() );
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Zone:</strong> ");
      out.print( offre.getZoneGeographique() );
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Durée:</strong> ");
      out.print( offre.getDureeMois() );
      out.write(" mois\n");
      out.write("                                        </div>\n");
      out.write("                                        ");
 if (offre.getRemuneration() != null) { 
      out.write("\n");
      out.write("                                            <div>\n");
      out.write("                                                <strong>Rémunération:</strong> ");
      out.print( offre.getRemuneration() );
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    ");
 if (offre.getDescription() != null) { 
      out.write("\n");
      out.write("                                        <div class=\"mt-md\">\n");
      out.write("                                            <strong>Description:</strong>\n");
      out.write("                                            <p class=\"text-secondary\">");
      out.print( offre.getDescription() );
      out.write("</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    ");
 if (offre.hasQuiz()) {
                                        List<QuizQuestion> questions = quizDAO.getQuestionsByQuizId(offre.getQuizId());
                                    
      out.write("\n");
      out.write("                                        <div class=\"mt-md quiz-display\">\n");
      out.write("                                            <strong>Quiz de Competences:</strong>\n");
      out.write("                                            <p class=\"text-muted\">");
      out.print( questions.size() );
      out.write(" questions - Score minimum: 75%</p>\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-sm btn-secondary\" onclick=\"toggleQuizQuestions(");
      out.print( offre.getId() );
      out.write(")\">\n");
      out.write("                                                Voir les questions\n");
      out.write("                                            </button>\n");
      out.write("                                            <div id=\"quiz-");
      out.print( offre.getId() );
      out.write("\" class=\"quiz-questions-display\" style=\"display: none;\">\n");
      out.write("                                                ");
 for (int i = 0; i < questions.size(); i++) {
                                                    QuizQuestion q = questions.get(i); 
      out.write("\n");
      out.write("                                                    <div class=\"quiz-question-display\">\n");
      out.write("                                                        <p><strong>Q");
      out.print( (i + 1) );
      out.write(":</strong> ");
      out.print( q.getQuestionText() );
      out.write("</p>\n");
      out.write("                                                        <ul class=\"quiz-options-list\">\n");
      out.write("                                                            <li ");
      out.print( q.getCorrectAnswer().equals("a") ? "class='correct-option'" : "" );
      out.write(">\n");
      out.write("                                                                A) ");
      out.print( q.getOptionA() );
      out.write("\n");
      out.write("                                                                ");
      out.print( q.getCorrectAnswer().equals("a") ? "(Correct)" : "" );
      out.write("\n");
      out.write("                                                            </li>\n");
      out.write("                                                            <li ");
      out.print( q.getCorrectAnswer().equals("b") ? "class='correct-option'" : "" );
      out.write(">\n");
      out.write("                                                                B) ");
      out.print( q.getOptionB() );
      out.write("\n");
      out.write("                                                                ");
      out.print( q.getCorrectAnswer().equals("b") ? "(Correct)" : "" );
      out.write("\n");
      out.write("                                                            </li>\n");
      out.write("                                                            <li ");
      out.print( q.getCorrectAnswer().equals("c") ? "class='correct-option'" : "" );
      out.write(">\n");
      out.write("                                                                C) ");
      out.print( q.getOptionC() );
      out.write("\n");
      out.write("                                                                ");
      out.print( q.getCorrectAnswer().equals("c") ? "(Correct)" : "" );
      out.write("\n");
      out.write("                                                            </li>\n");
      out.write("                                                            <li ");
      out.print( q.getCorrectAnswer().equals("d") ? "class='correct-option'" : "" );
      out.write(">\n");
      out.write("                                                                D) ");
      out.print( q.getOptionD() );
      out.write("\n");
      out.write("                                                                ");
      out.print( q.getCorrectAnswer().equals("d") ? "(Correct)" : "" );
      out.write("\n");
      out.write("                                                            </li>\n");
      out.write("                                                        </ul>\n");
      out.write("                                                    </div>\n");
      out.write("                                                ");
 } 
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <p class=\"text-center text-muted\">Cette entreprise n'a pas encore publié d'offres.</p>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function toggleQuizQuestions(offreId) {\n");
      out.write("            const quizDiv = document.getElementById('quiz-' + offreId);\n");
      out.write("            if (quizDiv.style.display === 'none') {\n");
      out.write("                quizDiv.style.display = 'block';\n");
      out.write("            } else {\n");
      out.write("                quizDiv.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
