/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:58:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.stages.model.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class entreprise_002dstagiaires_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.stages.model");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Entreprise entreprise = (Entreprise) session.getAttribute("entreprise");
    if (entreprise == null) {
        response.sendRedirect("login");
        return;
    }
    
    List<Candidature> stagiaires = (List<Candidature>) request.getAttribute("stagiaires");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Nos Stagiaires - StageConnect</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/navbar-entreprise.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>Nos Stagiaires</h1>\n");
      out.write("            <p>Liste des stagiaires acceptes dans votre entreprise</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"card\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                ");
 if (stagiaires != null && !stagiaires.isEmpty()) { 
      out.write("\n");
      out.write("                    <div class=\"offers-grid\">\n");
      out.write("                        ");
 for (Candidature stagiaire : stagiaires) { 
      out.write("\n");
      out.write("                            <div class=\"entreprise-card\">\n");
      out.write("                                <div class=\"entreprise-header\">\n");
      out.write("                                    <h3>");
      out.print( stagiaire.getApprenantFullName() );
      out.write("</h3>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"entreprise-details mb-md\">\n");
      out.write("                                    <div class=\"detail-item\">\n");
      out.write("                                        <strong>Email:</strong> ");
      out.print( stagiaire.getApprenantEmail() );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"detail-item\">\n");
      out.write("                                        <strong>Offre:</strong> ");
      out.print( stagiaire.getOffreTitre() );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"detail-item\">\n");
      out.write("                                        <strong>Date candidature:</strong> ");
      out.print( sdf.format(stagiaire.getDateCandidature()) );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    ");
 if (stagiaire.getDateReponse() != null) { 
      out.write("\n");
      out.write("                                        <div class=\"detail-item\">\n");
      out.write("                                            <strong>Accepté le:</strong> ");
      out.print( sdf.format(stagiaire.getDateReponse()) );
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    ");
 if (stagiaire.getQuizScore() != null) { 
      out.write("\n");
      out.write("                                        <div class=\"detail-item\">\n");
      out.write("                                            <strong>Score Quiz:</strong> \n");
      out.write("                                            <span class=\"badge ");
      out.print( stagiaire.getQuizScore() >= 75 ? "badge-success" : "badge-danger" );
      out.write("\">\n");
      out.write("                                                ");
      out.print( String.format("%.1f", stagiaire.getQuizScore()) );
      out.write("%\n");
      out.write("                                            </span>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <button onclick=\"viewDetails(");
      out.print( stagiaire.getId() );
      out.write(")\" class=\"btn btn-primary btn-block\">\n");
      out.write("                                    Voir détails\n");
      out.write("                                </button>\n");
      out.write("                                \n");
      out.write("                                <!-- Hidden details -->\n");
      out.write("                                <div id=\"details-");
      out.print( stagiaire.getId() );
      out.write("\" class=\"details-row mt-lg\" style=\"display: none; padding-top: var(--spacing-lg); border-top: 1px solid var(--color-border-light);\">\n");
      out.write("                                    ");
 if (stagiaire.getQuizAttemptId() != null && stagiaire.getQuizAttemptId() > 0) { 
      out.write("\n");
      out.write("                                        <div class=\"mb-md\">\n");
      out.write("                                            <strong>Résultats du Quiz:</strong>\n");
      out.write("                                            <p>Score: ");
      out.print( String.format("%.1f", stagiaire.getQuizScore()) );
      out.write("%</p>\n");
      out.write("                                            <a href=\"quiz?action=results&attemptId=");
      out.print( stagiaire.getQuizAttemptId() );
      out.write("\" class=\"btn btn-sm btn-info\">\n");
      out.write("                                                Voir les réponses détaillées\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    ");
 if (stagiaire.getLettreMotivation() != null && !stagiaire.getLettreMotivation().isEmpty()) { 
      out.write("\n");
      out.write("                                        <div class=\"mb-md\">\n");
      out.write("                                            <strong>Lettre de motivation:</strong>\n");
      out.write("                                            <p class=\"text-secondary\">\n");
      out.write("                                                ");
      out.print( stagiaire.getLettreMotivation() );
      out.write("\n");
      out.write("                                            </p>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    ");
 if (stagiaire.getCommentaireAdmin() != null && !stagiaire.getCommentaireAdmin().isEmpty()) { 
      out.write("\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Commentaire:</strong>\n");
      out.write("                                            <p class=\"text-secondary\">\n");
      out.write("                                                ");
      out.print( stagiaire.getCommentaireAdmin() );
      out.write("\n");
      out.write("                                            </p>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <p class=\"text-center text-muted\">\n");
      out.write("                        Vous n'avez pas encore accepté de stagiaires. \n");
      out.write("                        Consultez <a href=\"entreprise-dashboard\">vos candidatures</a> pour en accepter.\n");
      out.write("                    </p>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function viewDetails(id) {\n");
      out.write("            const details = document.getElementById('details-' + id);\n");
      out.write("            if (details.style.display === 'none') {\n");
      out.write("                details.style.display = 'block';\n");
      out.write("            } else {\n");
      out.write("                details.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
