/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:58:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.stages.model.*;
import com.stages.dao.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class entreprise_002doffres_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.stages.model");
    _jspx_imports_packages.add("com.stages.dao");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    Entreprise entreprise = (Entreprise) session.getAttribute("entreprise");
    if (entreprise == null) {
        response.sendRedirect("login");
        return;
    }
    
    List<OffreStage> offres = (List<OffreStage>) request.getAttribute("offres");
    if (offres == null) {
        offres = new ArrayList<>();
    }
    
    List<Quiz> quizzes = (List<Quiz>) request.getAttribute("quizzes");
    if (quizzes == null) {
        quizzes = new ArrayList<>();
    }
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    QuizDAO quizDAO = new QuizDAO();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Mes Offres - StageConnect</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/navbar-entreprise.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>Mes Offres de Stage</h1>\n");
      out.write("            <p>Gerez vos offres de stage</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");
 if (session.getAttribute("success") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert alert-success\">\n");
      out.write("                ");
      out.print( session.getAttribute("success") );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            ");
 session.removeAttribute("success"); 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        ");
 if (session.getAttribute("error") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert alert-error\">\n");
      out.write("                ");
      out.print( session.getAttribute("error") );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            ");
 session.removeAttribute("error"); 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"mb-lg\">\n");
      out.write("            <button onclick=\"openOfferModal()\" class=\"btn btn-primary\">\n");
      out.write("                Creer une nouvelle offre\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"card\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                ");
 if (offres != null && !offres.isEmpty()) { 
      out.write("\n");
      out.write("                    <div class=\"offers-list\">\n");
      out.write("                        ");
 for (OffreStage offre : offres) { 
      out.write("\n");
      out.write("                            <div class=\"offer-card mb-lg\" id=\"offer-");
      out.print( offre.getId() );
      out.write("\">\n");
      out.write("                                <div class=\"offer-header\">\n");
      out.write("                                    <h3>");
      out.print( offre.getTitre() );
      out.write("</h3>\n");
      out.write("                                    <div class=\"offer-actions\">\n");
      out.write("                                        <button onclick=\"openEditModalById(");
      out.print( offre.getId() );
      out.write(")\" \n");
      out.write("                                                class=\"btn btn-sm btn-secondary\">\n");
      out.write("                                            Modifier\n");
      out.write("                                        </button>\n");
      out.write("                                        <button onclick=\"confirmDeleteById(");
      out.print( offre.getId() );
      out.write(")\" \n");
      out.write("                                                class=\"btn btn-sm btn-danger\">\n");
      out.write("                                            Supprimer\n");
      out.write("                                        </button>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                                <div class=\"entreprise-info-grid\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <strong>Spécialité:</strong> ");
      out.print( offre.getSpecialite() );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <strong>Type:</strong> ");
      out.print( offre.getTypeStage() );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <strong>Zone:</strong> ");
      out.print( offre.getZoneGeographique() );
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <strong>Durée:</strong> ");
      out.print( offre.getDureeMois() );
      out.write(" mois\n");
      out.write("                                    </div>\n");
      out.write("                                    ");
 if (offre.getCreatedAt() != null) { 
      out.write("\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Créé le:</strong> ");
      out.print( sdf.format(offre.getCreatedAt()) );
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    ");
 if (offre.getRemuneration() != null) { 
      out.write("\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Rémunération:</strong> ");
      out.print( offre.getRemuneration() );
      out.write("\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    ");
 if (offre.hasQuiz()) { 
      out.write("\n");
      out.write("                                        <div>\n");
      out.write("                                            <strong>Quiz:</strong> \n");
      out.write("                                            <span class=\"badge badge-info\">Quiz Requis</span>\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-sm btn-info ml-sm\" onclick=\"openQuizModal(");
      out.print( offre.getId() );
      out.write(")\">\n");
      out.write("                                                Voir Questions\n");
      out.write("                                            </button>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                                ");
 if (offre.getDescription() != null && !offre.getDescription().isEmpty()) { 
      out.write("\n");
      out.write("                                    <div class=\"mb-md\">\n");
      out.write("                                        <strong>Description:</strong>\n");
      out.write("                                        <p class=\"text-secondary\">");
      out.print( offre.getDescription() );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                \n");
      out.write("                                ");
 if (offre.getCompetencesRequises() != null && !offre.getCompetencesRequises().isEmpty()) { 
      out.write("\n");
      out.write("                                    <div>\n");
      out.write("                                        <strong>Compétences requises:</strong>\n");
      out.write("                                        <p class=\"text-secondary\">");
      out.print( offre.getCompetencesRequises() );
      out.write("</p>\n");
      out.write("                                    </div>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                \n");
      out.write("                                <p class=\"text-muted mt-lg\">\n");
      out.write("                                    Publié le ");
      out.print( sdf.format(offre.getCreatedAt()) );
      out.write("\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <p class=\"text-center text-muted\">\n");
      out.write("                        Vous n'avez pas encore créé d'offres de stage. \n");
      out.write("                        Cliquez sur \"Creer une nouvelle offre\" pour commencer.\n");
      out.write("                    </p>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Create Offer Modal -->\n");
      out.write("    <div id=\"offerModal\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <span class=\"close\" onclick=\"closeOfferModal()\">&times;</span>\n");
      out.write("            <h2>Creer une offre de stage</h2>\n");
      out.write("            <form action=\"entreprise-offres\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"create\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"titre\">Titre de l'offre *</label>\n");
      out.write("                    <input type=\"text\" id=\"titre\" name=\"titre\" required\n");
      out.write("                           placeholder=\"Ex: Développeur Web Full Stack\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"description\">Description *</label>\n");
      out.write("                    <textarea id=\"description\" name=\"description\" rows=\"4\" required minlength=\"50\"\n");
      out.write("                              placeholder=\"Décrivez l'offre de stage (minimum 50 caractères)...\"></textarea>\n");
      out.write("                    <small class=\"form-text\">Minimum 50 caractères</small>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"specialite\">Spécialité *</label>\n");
      out.write("                        <select id=\"specialite\" name=\"specialite\" required>\n");
      out.write("                            <option value=\"\">-- Sélectionnez --</option>\n");
      out.write("                            <option value=\"Développement Web et Mobile\">Développement Web et Mobile</option>\n");
      out.write("                            <option value=\"Développement Web\">Développement Web</option>\n");
      out.write("                            <option value=\"Développement Mobile\">Développement Mobile</option>\n");
      out.write("                            <option value=\"Data Science\">Data Science</option>\n");
      out.write("                            <option value=\"Cyber Sécurité\">Cyber Sécurité</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"typeStage\">Type de stage *</label>\n");
      out.write("                        <select id=\"typeStage\" name=\"typeStage\" required>\n");
      out.write("                            <option value=\"\">-- Sélectionnez --</option>\n");
      out.write("                            <option value=\"Présentiel\">Présentiel</option>\n");
      out.write("                            <option value=\"Apprentissage\">Apprentissage</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"zone\">Zone géographique *</label>\n");
      out.write("                        <select id=\"zone\" name=\"zone\" required>\n");
      out.write("                            <option value=\"\">-- Sélectionnez --</option>\n");
      out.write("                            <option value=\"Alger\">Alger</option>\n");
      out.write("                            <option value=\"Oran\">Oran</option>\n");
      out.write("                            <option value=\"Constantine\">Constantine</option>\n");
      out.write("                            <option value=\"Annaba\">Annaba</option>\n");
      out.write("                            <option value=\"Blida\">Blida</option>\n");
      out.write("                            <option value=\"Sétif\">Sétif</option>\n");
      out.write("                            <option value=\"Tipaza\">Tipaza</option>\n");
      out.write("                            <option value=\"Béjaïa\">Béjaïa</option>\n");
      out.write("                            <option value=\"Batna\">Batna</option>\n");
      out.write("                            <option value=\"Tlemcen\">Tlemcen</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"dureeMois\">Durée (en mois) *</label>\n");
      out.write("                        <input type=\"number\" id=\"dureeMois\" name=\"dureeMois\" required\n");
      out.write("                               min=\"1\" max=\"48\" placeholder=\"6\">\n");
      out.write("                        <small class=\"form-text\">Maximum 48 mois (4 ans)</small>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"remuneration\">Rémunération</label>\n");
      out.write("                    <input type=\"text\" id=\"remuneration\" name=\"remuneration\"\n");
      out.write("                           placeholder=\"Ex: 80 000 DZD/mois\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"competences\">Compétences requises</label>\n");
      out.write("                    <textarea id=\"competences\" name=\"competences\" rows=\"3\"\n");
      out.write("                              placeholder=\"Listez les compétences nécessaires...\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <hr class=\"my-lg\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\" id=\"includeQuiz\" name=\"includeQuiz\" onchange=\"toggleQuizSection()\">\n");
      out.write("                        Ajouter un quiz de competences\n");
      out.write("                    </label>\n");
      out.write("                    <small class=\"form-text\">Les candidats devront completer le quiz pour postuler</small>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div id=\"quizSection\" style=\"display: none;\">\n");
      out.write("                    <div class=\"quiz-inline-section\">\n");
      out.write("                        <h3>Questions du Quiz</h3>\n");
      out.write("                        <small class=\"form-text mb-md\">Ajoutez au moins 3 questions (maximum 10)</small>\n");
      out.write("                        \n");
      out.write("                        <div id=\"questionsContainer\">\n");
      out.write("                            <!-- Questions will be added here dynamically -->\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary btn-block mt-md\" onclick=\"addQuizQuestion()\">\n");
      out.write("                            Ajouter une question\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"modal-actions\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Creer l'offre</button>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"closeOfferModal()\">Annuler</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Edit Offer Modal -->\n");
      out.write("    <div id=\"editOfferModal\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <span class=\"close\" onclick=\"closeEditModal()\">&times;</span>\n");
      out.write("            <h2>Modifier l'offre de stage</h2>\n");
      out.write("            <form id=\"editOfferForm\" action=\"entreprise-offres\" method=\"post\" onsubmit=\"return validateEditForm(event)\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"edit\">\n");
      out.write("                <input type=\"hidden\" id=\"editOffreId\" name=\"offreId\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editTitre\">Titre de l'offre *</label>\n");
      out.write("                    <input type=\"text\" id=\"editTitre\" name=\"titre\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editDescription\">Description *</label>\n");
      out.write("                    <textarea id=\"editDescription\" name=\"description\" rows=\"4\" required minlength=\"50\"></textarea>\n");
      out.write("                    <small class=\"form-text\">Minimum 50 caractères</small>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"editSpecialite\">Spécialité *</label>\n");
      out.write("                        <select id=\"editSpecialite\" name=\"specialite\" required>\n");
      out.write("                            <option value=\"\">-- Sélectionnez --</option>\n");
      out.write("                            <option value=\"Développement Web et Mobile\">Développement Web et Mobile</option>\n");
      out.write("                            <option value=\"Développement Web\">Développement Web</option>\n");
      out.write("                            <option value=\"Développement Mobile\">Développement Mobile</option>\n");
      out.write("                            <option value=\"Data Science\">Data Science</option>\n");
      out.write("                            <option value=\"Cyber Sécurité\">Cyber Sécurité</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"editTypeStage\">Type de stage *</label>\n");
      out.write("                        <select id=\"editTypeStage\" name=\"typeStage\" required>\n");
      out.write("                            <option value=\"\">-- Sélectionnez --</option>\n");
      out.write("                            <option value=\"Présentiel\">Présentiel</option>\n");
      out.write("                            <option value=\"Apprentissage\">Apprentissage</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"editZone\">Zone géographique *</label>\n");
      out.write("                        <select id=\"editZone\" name=\"zone\" required>\n");
      out.write("                            <option value=\"\">-- Sélectionnez --</option>\n");
      out.write("                            <option value=\"Alger\">Alger</option>\n");
      out.write("                            <option value=\"Oran\">Oran</option>\n");
      out.write("                            <option value=\"Constantine\">Constantine</option>\n");
      out.write("                            <option value=\"Annaba\">Annaba</option>\n");
      out.write("                            <option value=\"Blida\">Blida</option>\n");
      out.write("                            <option value=\"Sétif\">Sétif</option>\n");
      out.write("                            <option value=\"Tipaza\">Tipaza</option>\n");
      out.write("                            <option value=\"Béjaïa\">Béjaïa</option>\n");
      out.write("                            <option value=\"Batna\">Batna</option>\n");
      out.write("                            <option value=\"Tlemcen\">Tlemcen</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"editDureeMois\">Durée (en mois) *</label>\n");
      out.write("                        <input type=\"number\" id=\"editDureeMois\" name=\"dureeMois\" required min=\"1\" max=\"48\">\n");
      out.write("                        <small class=\"form-text\">Maximum 48 mois (4 ans)</small>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editRemuneration\">Rémunération</label>\n");
      out.write("                    <input type=\"text\" id=\"editRemuneration\" name=\"remuneration\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editCompetences\">Compétences requises</label>\n");
      out.write("                    <textarea id=\"editCompetences\" name=\"competences\" rows=\"3\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <hr class=\"my-lg\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>\n");
      out.write("                        <input type=\"checkbox\" id=\"editIncludeQuiz\" name=\"includeQuiz\" onchange=\"toggleEditQuizSection()\">\n");
      out.write("                        Ajouter/Modifier le quiz de competences\n");
      out.write("                    </label>\n");
      out.write("                    <small class=\"form-text\">Les candidats devront completer le quiz pour postuler</small>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div id=\"editQuizSection\" style=\"display: none;\">\n");
      out.write("                    <div class=\"quiz-inline-section\">\n");
      out.write("                        <h3>Questions du Quiz</h3>\n");
      out.write("                        <small class=\"form-text mb-md\">Ajoutez au moins 3 questions (maximum 10)</small>\n");
      out.write("                        \n");
      out.write("                        <div id=\"editQuestionsContainer\">\n");
      out.write("                            <!-- Questions will be loaded/added here -->\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary btn-block mt-md\" onclick=\"addEditQuizQuestion()\">\n");
      out.write("                            Ajouter une question\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"modal-actions\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Sauvegarder</button>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"closeEditModal()\">Annuler</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Delete Confirmation Modal -->\n");
      out.write("    <div id=\"deleteModal\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <span class=\"close\" onclick=\"closeDeleteModal()\">&times;</span>\n");
      out.write("            <h2>Confirmer la suppression</h2>\n");
      out.write("            <p id=\"deleteMessage\"></p>\n");
      out.write("            <form action=\"entreprise-offres\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"delete\">\n");
      out.write("                <input type=\"hidden\" id=\"deleteOffreId\" name=\"offreId\">\n");
      out.write("                \n");
      out.write("                <div class=\"modal-actions\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger\">Supprimer</button>\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" onclick=\"closeDeleteModal()\">Annuler</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Quiz Questions View Modal -->\n");
      out.write("    <div id=\"quizModal\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content modal-large\">\n");
      out.write("            <span class=\"close\" onclick=\"closeQuizModal()\">&times;</span>\n");
      out.write("            <h2 id=\"quizModalTitle\">Questions du Quiz</h2>\n");
      out.write("            <div id=\"quizModalContent\" class=\"quiz-modal-body\">\n");
      out.write("                <!-- Quiz questions will be populated here -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // Store all offer data - populated from server\n");
      out.write("        var offerData = {};\n");
      out.write("        var offerQuizData = {};\n");
      out.write("        \n");
      out.write("        ");
 
        if (offres != null && !offres.isEmpty()) {
            for (OffreStage offre : offres) { 
                String titre = offre.getTitre() != null ? offre.getTitre().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") : "";
                String description = offre.getDescription() != null ? offre.getDescription().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") : "";
                String remuneration = offre.getRemuneration() != null ? offre.getRemuneration().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"") : "";
                String competences = offre.getCompetencesRequises() != null ? offre.getCompetencesRequises().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") : "";
        
      out.write("\n");
      out.write("        offerData[");
      out.print( offre.getId() );
      out.write("] = {\n");
      out.write("            id: ");
      out.print( offre.getId() );
      out.write(",\n");
      out.write("            titre: '");
      out.print( titre );
      out.write("',\n");
      out.write("            description: '");
      out.print( description );
      out.write("',\n");
      out.write("            specialite: '");
      out.print( offre.getSpecialite() );
      out.write("',\n");
      out.write("            typeStage: '");
      out.print( offre.getTypeStage() );
      out.write("',\n");
      out.write("            zone: '");
      out.print( offre.getZoneGeographique() );
      out.write("',\n");
      out.write("            dureeMois: ");
      out.print( offre.getDureeMois() );
      out.write(",\n");
      out.write("            remuneration: '");
      out.print( remuneration );
      out.write("',\n");
      out.write("            competences: '");
      out.print( competences );
      out.write("',\n");
      out.write("            quizId: ");
      out.print( offre.hasQuiz() && offre.getQuizId() != null ? offre.getQuizId() : "null" );
      out.write("\n");
      out.write("        };\n");
      out.write("        ");

                // Load quiz questions if this offer has a quiz
                if (offre.hasQuiz() && offre.getQuizId() != null) {
                    List<QuizQuestion> questions = quizDAO.getQuestionsByQuizId(offre.getQuizId());
                    if (questions != null && !questions.isEmpty()) {
        
      out.write("\n");
      out.write("        offerQuizData[");
      out.print( offre.getId() );
      out.write("] = {\n");
      out.write("            quizId: ");
      out.print( offre.getQuizId() );
      out.write(",\n");
      out.write("            questions: [\n");
      out.write("                ");
 
                for (int i = 0; i < questions.size(); i++) { 
                    QuizQuestion q = questions.get(i);
                    if (i > 0) out.print(",");
                    String questionText = q.getQuestionText() != null ? q.getQuestionText().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") : "";
                    String optionA = q.getOptionA() != null ? q.getOptionA().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"") : "";
                    String optionB = q.getOptionB() != null ? q.getOptionB().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"") : "";
                    String optionC = q.getOptionC() != null ? q.getOptionC().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"") : "";
                    String optionD = q.getOptionD() != null ? q.getOptionD().replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"") : "";
                    String correctAnswer = q.getCorrectAnswer() != null ? q.getCorrectAnswer() : "";
                
      out.write("\n");
      out.write("                {\n");
      out.write("                    id: ");
      out.print( q.getId() );
      out.write(",\n");
      out.write("                    questionText: '");
      out.print( questionText );
      out.write("',\n");
      out.write("                    optionA: '");
      out.print( optionA );
      out.write("',\n");
      out.write("                    optionB: '");
      out.print( optionB );
      out.write("',\n");
      out.write("                    optionC: '");
      out.print( optionC );
      out.write("',\n");
      out.write("                    optionD: '");
      out.print( optionD );
      out.write("',\n");
      out.write("                    correctAnswer: '");
      out.print( correctAnswer );
      out.write("',\n");
      out.write("                    points: ");
      out.print( q.getPoints() );
      out.write("\n");
      out.write("                }\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ]\n");
      out.write("        };\n");
      out.write("        ");

                    }
                }
            }
        }
        
      out.write("\n");
      out.write("        \n");
      out.write("        function openOfferModal() {\n");
      out.write("            document.getElementById('offerModal').style.display = 'block';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function closeOfferModal() {\n");
      out.write("            document.getElementById('offerModal').style.display = 'none';\n");
      out.write("            document.getElementById('includeQuiz').checked = false;\n");
      out.write("            document.getElementById('quizSection').style.display = 'none';\n");
      out.write("            document.getElementById('questionsContainer').innerHTML = '';\n");
      out.write("            questionCount = 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        var questionCount = 0;\n");
      out.write("        var questionIdCounter = 0;\n");
      out.write("        \n");
      out.write("        function toggleQuizSection() {\n");
      out.write("            var checkbox = document.getElementById('includeQuiz');\n");
      out.write("            var section = document.getElementById('quizSection');\n");
      out.write("            if (checkbox.checked) {\n");
      out.write("                section.style.display = 'block';\n");
      out.write("                if (questionCount === 0) {\n");
      out.write("                    addQuizQuestion();\n");
      out.write("                    addQuizQuestion();\n");
      out.write("                    addQuizQuestion();\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                section.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function addQuizQuestion() {\n");
      out.write("            var container = document.getElementById('questionsContainer');\n");
      out.write("            var actualCount = container.querySelectorAll('.quiz-question-item').length;\n");
      out.write("            \n");
      out.write("            if (actualCount >= 10) {\n");
      out.write("                alert('Maximum 10 questions par quiz');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            questionIdCounter++;\n");
      out.write("            var currentId = questionIdCounter;\n");
      out.write("            var num = actualCount + 1;\n");
      out.write("            \n");
      out.write("            var questionDiv = document.createElement('div');\n");
      out.write("            questionDiv.className = 'quiz-question-item';\n");
      out.write("            questionDiv.setAttribute('data-question-id', currentId);\n");
      out.write("            questionDiv.innerHTML = \n");
      out.write("                '<div class=\"question-header\">' +\n");
      out.write("                    '<span class=\"question-number\">Question ' + num + '</span>' +\n");
      out.write("                    '<button type=\"button\" class=\"btn-remove-question\" onclick=\"removeQuizQuestion(' + currentId + ')\">Supprimer</button>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-group\">' +\n");
      out.write("                    '<label>Texte de la question *</label>' +\n");
      out.write("                    '<input type=\"text\" name=\"question_' + num + '\" class=\"question-input\" required placeholder=\"Ex: Quel est le langage de programmation cote client?\">' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-row\">' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option A *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionA_' + num + '\" class=\"optionA-input\" required placeholder=\"Option A\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option B *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionB_' + num + '\" class=\"optionB-input\" required placeholder=\"Option B\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-row\">' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option C *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionC_' + num + '\" class=\"optionC-input\" required placeholder=\"Option C\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option D *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionD_' + num + '\" class=\"optionD-input\" required placeholder=\"Option D\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-row\">' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Reponse correcte *</label>' +\n");
      out.write("                        '<select name=\"correctAnswer_' + num + '\" class=\"correctAnswer-input\" required>' +\n");
      out.write("                            '<option value=\"\">-- Selectionnez --</option>' +\n");
      out.write("                            '<option value=\"a\">Option A</option>' +\n");
      out.write("                            '<option value=\"b\">Option B</option>' +\n");
      out.write("                            '<option value=\"c\">Option C</option>' +\n");
      out.write("                            '<option value=\"d\">Option D</option>' +\n");
      out.write("                        '</select>' +\n");
      out.write("                    '</div>' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Points</label>' +\n");
      out.write("                        '<input type=\"number\" name=\"points_' + num + '\" class=\"points-input\" value=\"5\" min=\"1\" max=\"10\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>';\n");
      out.write("            \n");
      out.write("            container.appendChild(questionDiv);\n");
      out.write("            questionCount = actualCount + 1;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function removeQuizQuestion(id) {\n");
      out.write("            var container = document.getElementById('questionsContainer');\n");
      out.write("            var currentQuestions = container.querySelectorAll('.quiz-question-item');\n");
      out.write("            \n");
      out.write("            if (currentQuestions.length <= 3) {\n");
      out.write("                alert('Le quiz doit contenir au moins 3 questions.');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            var questionDiv = container.querySelector('[data-question-id=\"' + id + '\"]');\n");
      out.write("            if (questionDiv) {\n");
      out.write("                questionDiv.remove();\n");
      out.write("                var questions = container.querySelectorAll('.quiz-question-item');\n");
      out.write("                questionCount = questions.length;\n");
      out.write("                questions.forEach(function(q, index) {\n");
      out.write("                    var num = index + 1;\n");
      out.write("                    q.querySelector('.question-number').textContent = 'Question ' + num;\n");
      out.write("                    q.querySelector('.question-input').name = 'question_' + num;\n");
      out.write("                    q.querySelector('.optionA-input').name = 'optionA_' + num;\n");
      out.write("                    q.querySelector('.optionB-input').name = 'optionB_' + num;\n");
      out.write("                    q.querySelector('.optionC-input').name = 'optionC_' + num;\n");
      out.write("                    q.querySelector('.optionD-input').name = 'optionD_' + num;\n");
      out.write("                    q.querySelector('.correctAnswer-input').name = 'correctAnswer_' + num;\n");
      out.write("                    q.querySelector('.points-input').name = 'points_' + num;\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        var editQuestionCount = 0;\n");
      out.write("        var editQuestionIdCounter = 0;\n");
      out.write("        \n");
      out.write("        function toggleEditQuizSection() {\n");
      out.write("            var checkbox = document.getElementById('editIncludeQuiz');\n");
      out.write("            var section = document.getElementById('editQuizSection');\n");
      out.write("            if (checkbox.checked) {\n");
      out.write("                section.style.display = 'block';\n");
      out.write("            } else {\n");
      out.write("                section.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function addEditQuizQuestion() {\n");
      out.write("            var container = document.getElementById('editQuestionsContainer');\n");
      out.write("            var actualCount = container.querySelectorAll('.quiz-question-item').length;\n");
      out.write("            \n");
      out.write("            if (actualCount >= 10) {\n");
      out.write("                alert('Maximum 10 questions par quiz');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            editQuestionIdCounter++;\n");
      out.write("            var currentId = editQuestionIdCounter;\n");
      out.write("            var num = actualCount + 1;\n");
      out.write("            \n");
      out.write("            var questionDiv = document.createElement('div');\n");
      out.write("            questionDiv.className = 'quiz-question-item';\n");
      out.write("            questionDiv.setAttribute('data-question-id', currentId);\n");
      out.write("            questionDiv.innerHTML = \n");
      out.write("                '<div class=\"question-header\">' +\n");
      out.write("                    '<span class=\"question-number\">Question ' + num + '</span>' +\n");
      out.write("                    '<button type=\"button\" class=\"btn-remove-question\" onclick=\"removeEditQuizQuestion(' + currentId + ')\">Supprimer</button>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-group\">' +\n");
      out.write("                    '<label>Texte de la question *</label>' +\n");
      out.write("                    '<input type=\"text\" name=\"question_' + num + '\" class=\"question-input\" required placeholder=\"Ex: Quel est le langage de programmation cote client?\">' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-row\">' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option A *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionA_' + num + '\" class=\"optionA-input\" required placeholder=\"Option A\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option B *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionB_' + num + '\" class=\"optionB-input\" required placeholder=\"Option B\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-row\">' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option C *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionC_' + num + '\" class=\"optionC-input\" required placeholder=\"Option C\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Option D *</label>' +\n");
      out.write("                        '<input type=\"text\" name=\"optionD_' + num + '\" class=\"optionD-input\" required placeholder=\"Option D\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<div class=\"form-row\">' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Reponse correcte *</label>' +\n");
      out.write("                        '<select name=\"correctAnswer_' + num + '\" class=\"correctAnswer-input\" required>' +\n");
      out.write("                            '<option value=\"\">-- Selectionnez --</option>' +\n");
      out.write("                            '<option value=\"a\">Option A</option>' +\n");
      out.write("                            '<option value=\"b\">Option B</option>' +\n");
      out.write("                            '<option value=\"c\">Option C</option>' +\n");
      out.write("                            '<option value=\"d\">Option D</option>' +\n");
      out.write("                        '</select>' +\n");
      out.write("                    '</div>' +\n");
      out.write("                    '<div class=\"form-group\">' +\n");
      out.write("                        '<label>Points</label>' +\n");
      out.write("                        '<input type=\"number\" name=\"points_' + num + '\" class=\"points-input\" value=\"5\" min=\"1\" max=\"10\">' +\n");
      out.write("                    '</div>' +\n");
      out.write("                '</div>';\n");
      out.write("            \n");
      out.write("            container.appendChild(questionDiv);\n");
      out.write("            editQuestionCount = actualCount + 1;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function removeEditQuizQuestion(id) {\n");
      out.write("            var container = document.getElementById('editQuestionsContainer');\n");
      out.write("            var currentQuestions = container.querySelectorAll('.quiz-question-item');\n");
      out.write("            \n");
      out.write("            if (currentQuestions.length <= 3) {\n");
      out.write("                alert('Le quiz doit contenir au moins 3 questions.');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            var questionDiv = container.querySelector('[data-question-id=\"' + id + '\"]');\n");
      out.write("            if (questionDiv) {\n");
      out.write("                questionDiv.remove();\n");
      out.write("                var questions = container.querySelectorAll('.quiz-question-item');\n");
      out.write("                editQuestionCount = questions.length;\n");
      out.write("                questions.forEach(function(q, index) {\n");
      out.write("                    var num = index + 1;\n");
      out.write("                    q.querySelector('.question-number').textContent = 'Question ' + num;\n");
      out.write("                    q.querySelector('.question-input').name = 'question_' + num;\n");
      out.write("                    q.querySelector('.optionA-input').name = 'optionA_' + num;\n");
      out.write("                    q.querySelector('.optionB-input').name = 'optionB_' + num;\n");
      out.write("                    q.querySelector('.optionC-input').name = 'optionC_' + num;\n");
      out.write("                    q.querySelector('.optionD-input').name = 'optionD_' + num;\n");
      out.write("                    q.querySelector('.correctAnswer-input').name = 'correctAnswer_' + num;\n");
      out.write("                    q.querySelector('.points-input').name = 'points_' + num;\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function openQuizModal(offerId) {\n");
      out.write("            const offer = offerData[offerId];\n");
      out.write("            const quizData = offerQuizData[offerId];\n");
      out.write("            \n");
      out.write("            if (!offer || !quizData) {\n");
      out.write("                alert('Aucune question trouvee pour cette offre.');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            // Set modal title\n");
      out.write("            document.getElementById('quizModalTitle').textContent = 'Quiz: ' + offer.titre;\n");
      out.write("            \n");
      out.write("            // Build quiz content\n");
      out.write("            let content = '<div class=\"quiz-questions-display\">';\n");
      out.write("            \n");
      out.write("            quizData.questions.forEach(function(q, index) {\n");
      out.write("                content += '<div class=\"quiz-question-display-item\">';\n");
      out.write("                content += '    <p class=\"question-text\"><strong>Q' + (index + 1) + ':</strong> ' + q.questionText + '</p>';\n");
      out.write("                content += '    <div class=\"options-list\">';\n");
      out.write("                content += '        <p>A) ' + q.optionA + '</p>';\n");
      out.write("                content += '        <p>B) ' + q.optionB + '</p>';\n");
      out.write("                content += '        <p>C) ' + q.optionC + '</p>';\n");
      out.write("                content += '        <p>D) ' + q.optionD + '</p>';\n");
      out.write("                content += '    </div>';\n");
      out.write("                content += '    <p class=\"correct-answer-display\">';\n");
      out.write("                content += '        <strong>Reponse correcte:</strong> ';\n");
      out.write("                content += '        <span class=\"text-success\">' + q.correctAnswer.toUpperCase() + '</span>';\n");
      out.write("                content += '        (' + q.points + ' points)';\n");
      out.write("                content += '    </p>';\n");
      out.write("                content += '</div>';\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            content += '</div>';\n");
      out.write("            \n");
      out.write("            // Set content\n");
      out.write("            document.getElementById('quizModalContent').innerHTML = content;\n");
      out.write("            \n");
      out.write("            // Show modal\n");
      out.write("            document.getElementById('quizModal').style.display = 'block';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function closeQuizModal() {\n");
      out.write("            document.getElementById('quizModal').style.display = 'none';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        let originalFormData = {};\n");
      out.write("        \n");
      out.write("        function captureOriginalFormData() {\n");
      out.write("            const form = document.getElementById('editOfferForm');\n");
      out.write("            originalFormData = {\n");
      out.write("                titre: form.querySelector('#editTitre').value,\n");
      out.write("                description: form.querySelector('#editDescription').value,\n");
      out.write("                specialite: form.querySelector('#editSpecialite').value,\n");
      out.write("                typeStage: form.querySelector('#editTypeStage').value,\n");
      out.write("                zone: form.querySelector('#editZone').value,\n");
      out.write("                dureeMois: form.querySelector('#editDureeMois').value,\n");
      out.write("                remuneration: form.querySelector('#editRemuneration').value,\n");
      out.write("                competences: form.querySelector('#editCompetences').value,\n");
      out.write("                includeQuiz: form.querySelector('#editIncludeQuiz').checked,\n");
      out.write("                questions: []\n");
      out.write("            };\n");
      out.write("            \n");
      out.write("            // Capture quiz questions if present\n");
      out.write("            const questionItems = form.querySelectorAll('.quiz-question-item');\n");
      out.write("            questionItems.forEach(function(item) {\n");
      out.write("                const questionData = {\n");
      out.write("                    text: item.querySelector('.question-input').value,\n");
      out.write("                    optionA: item.querySelector('.optionA-input').value,\n");
      out.write("                    optionB: item.querySelector('.optionB-input').value,\n");
      out.write("                    optionC: item.querySelector('.optionC-input').value,\n");
      out.write("                    optionD: item.querySelector('.optionD-input').value,\n");
      out.write("                    correctAnswer: item.querySelector('.correctAnswer-input').value,\n");
      out.write("                    points: item.querySelector('.points-input').value\n");
      out.write("                };\n");
      out.write("                originalFormData.questions.push(questionData);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function validateEditForm(event) {\n");
      out.write("            const form = document.getElementById('editOfferForm');\n");
      out.write("            const currentData = {\n");
      out.write("                titre: form.querySelector('#editTitre').value,\n");
      out.write("                description: form.querySelector('#editDescription').value,\n");
      out.write("                specialite: form.querySelector('#editSpecialite').value,\n");
      out.write("                typeStage: form.querySelector('#editTypeStage').value,\n");
      out.write("                zone: form.querySelector('#editZone').value,\n");
      out.write("                dureeMois: form.querySelector('#editDureeMois').value,\n");
      out.write("                remuneration: form.querySelector('#editRemuneration').value,\n");
      out.write("                competences: form.querySelector('#editCompetences').value,\n");
      out.write("                includeQuiz: form.querySelector('#editIncludeQuiz').checked,\n");
      out.write("                questions: []\n");
      out.write("            };\n");
      out.write("            \n");
      out.write("            // Capture current quiz questions\n");
      out.write("            const questionItems = form.querySelectorAll('.quiz-question-item');\n");
      out.write("            questionItems.forEach(function(item) {\n");
      out.write("                const questionData = {\n");
      out.write("                    text: item.querySelector('.question-input').value,\n");
      out.write("                    optionA: item.querySelector('.optionA-input').value,\n");
      out.write("                    optionB: item.querySelector('.optionB-input').value,\n");
      out.write("                    optionC: item.querySelector('.optionC-input').value,\n");
      out.write("                    optionD: item.querySelector('.optionD-input').value,\n");
      out.write("                    correctAnswer: item.querySelector('.correctAnswer-input').value,\n");
      out.write("                    points: item.querySelector('.points-input').value\n");
      out.write("                };\n");
      out.write("                currentData.questions.push(questionData);\n");
      out.write("            });\n");
      out.write("            \n");
      out.write("            // Compare offer fields\n");
      out.write("            let hasChanges = false;\n");
      out.write("            if (currentData.titre !== originalFormData.titre ||\n");
      out.write("                currentData.description !== originalFormData.description ||\n");
      out.write("                currentData.specialite !== originalFormData.specialite ||\n");
      out.write("                currentData.typeStage !== originalFormData.typeStage ||\n");
      out.write("                currentData.zone !== originalFormData.zone ||\n");
      out.write("                currentData.dureeMois !== originalFormData.dureeMois ||\n");
      out.write("                currentData.remuneration !== originalFormData.remuneration ||\n");
      out.write("                currentData.competences !== originalFormData.competences ||\n");
      out.write("                currentData.includeQuiz !== originalFormData.includeQuiz) {\n");
      out.write("                hasChanges = true;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            // Compare quiz questions\n");
      out.write("            if (!hasChanges) {\n");
      out.write("                if (currentData.questions.length !== originalFormData.questions.length) {\n");
      out.write("                    hasChanges = true;\n");
      out.write("                } else {\n");
      out.write("                    for (let i = 0; i < currentData.questions.length; i++) {\n");
      out.write("                        const curr = currentData.questions[i];\n");
      out.write("                        const orig = originalFormData.questions[i];\n");
      out.write("                        if (curr.text !== orig.text ||\n");
      out.write("                            curr.optionA !== orig.optionA ||\n");
      out.write("                            curr.optionB !== orig.optionB ||\n");
      out.write("                            curr.optionC !== orig.optionC ||\n");
      out.write("                            curr.optionD !== orig.optionD ||\n");
      out.write("                            curr.correctAnswer !== orig.correctAnswer ||\n");
      out.write("                            curr.points !== orig.points) {\n");
      out.write("                            hasChanges = true;\n");
      out.write("                            break;\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            if (!hasChanges) {\n");
      out.write("                event.preventDefault();\n");
      out.write("                alert('Aucune modification detectee. Veuillez modifier au moins un champ avant de soumettre.');\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function openEditModalById(id) {\n");
      out.write("            var offer = offerData[id];\n");
      out.write("            if (!offer) {\n");
      out.write("                alert('Erreur: Offre introuvable');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.getElementById('editOffreId').value = offer.id;\n");
      out.write("            document.getElementById('editTitre').value = offer.titre;\n");
      out.write("            document.getElementById('editDescription').value = offer.description;\n");
      out.write("            document.getElementById('editSpecialite').value = offer.specialite;\n");
      out.write("            document.getElementById('editTypeStage').value = offer.typeStage;\n");
      out.write("            document.getElementById('editZone').value = offer.zone;\n");
      out.write("            document.getElementById('editDureeMois').value = offer.dureeMois;\n");
      out.write("            document.getElementById('editRemuneration').value = offer.remuneration;\n");
      out.write("            document.getElementById('editCompetences').value = offer.competences;\n");
      out.write("            \n");
      out.write("            document.getElementById('editIncludeQuiz').checked = false;\n");
      out.write("            document.getElementById('editQuizSection').style.display = 'none';\n");
      out.write("            document.getElementById('editQuestionsContainer').innerHTML = '';\n");
      out.write("            editQuestionCount = 0;\n");
      out.write("            editQuestionIdCounter = 0;\n");
      out.write("            \n");
      out.write("            if (offer.quizId && offerQuizData[id]) {\n");
      out.write("                var quizData = offerQuizData[id];\n");
      out.write("                document.getElementById('editIncludeQuiz').checked = true;\n");
      out.write("                document.getElementById('editQuizSection').style.display = 'block';\n");
      out.write("                \n");
      out.write("                quizData.questions.forEach(function(q, index) {\n");
      out.write("                    editQuestionIdCounter++;\n");
      out.write("                    var currentId = editQuestionIdCounter;\n");
      out.write("                    var container = document.getElementById('editQuestionsContainer');\n");
      out.write("                    var num = index + 1;\n");
      out.write("                    \n");
      out.write("                    var selectedA = q.correctAnswer === 'a' ? 'selected' : '';\n");
      out.write("                    var selectedB = q.correctAnswer === 'b' ? 'selected' : '';\n");
      out.write("                    var selectedC = q.correctAnswer === 'c' ? 'selected' : '';\n");
      out.write("                    var selectedD = q.correctAnswer === 'd' ? 'selected' : '';\n");
      out.write("                    \n");
      out.write("                    var questionDiv = document.createElement('div');\n");
      out.write("                    questionDiv.className = 'quiz-question-item';\n");
      out.write("                    questionDiv.setAttribute('data-question-id', currentId);\n");
      out.write("                    questionDiv.innerHTML = \n");
      out.write("                        '<div class=\"question-header\">' +\n");
      out.write("                            '<span class=\"question-number\">Question ' + num + '</span>' +\n");
      out.write("                            '<button type=\"button\" class=\"btn-remove-question\" onclick=\"removeEditQuizQuestion(' + currentId + ')\">Supprimer</button>' +\n");
      out.write("                        '</div>' +\n");
      out.write("                        '<div class=\"form-group\">' +\n");
      out.write("                            '<label>Texte de la question *</label>' +\n");
      out.write("                            '<input type=\"text\" name=\"question_' + num + '\" class=\"question-input\" required value=\"' + q.questionText + '\" placeholder=\"Ex: Quel est le langage de programmation cote client?\">' +\n");
      out.write("                        '</div>' +\n");
      out.write("                        '<div class=\"form-row\">' +\n");
      out.write("                            '<div class=\"form-group\">' +\n");
      out.write("                                '<label>Option A *</label>' +\n");
      out.write("                                '<input type=\"text\" name=\"optionA_' + num + '\" class=\"optionA-input\" required value=\"' + q.optionA + '\" placeholder=\"Option A\">' +\n");
      out.write("                            '</div>' +\n");
      out.write("                            '<div class=\"form-group\">' +\n");
      out.write("                                '<label>Option B *</label>' +\n");
      out.write("                                '<input type=\"text\" name=\"optionB_' + num + '\" class=\"optionB-input\" required value=\"' + q.optionB + '\" placeholder=\"Option B\">' +\n");
      out.write("                            '</div>' +\n");
      out.write("                        '</div>' +\n");
      out.write("                        '<div class=\"form-row\">' +\n");
      out.write("                            '<div class=\"form-group\">' +\n");
      out.write("                                '<label>Option C *</label>' +\n");
      out.write("                                '<input type=\"text\" name=\"optionC_' + num + '\" class=\"optionC-input\" required value=\"' + q.optionC + '\" placeholder=\"Option C\">' +\n");
      out.write("                            '</div>' +\n");
      out.write("                            '<div class=\"form-group\">' +\n");
      out.write("                                '<label>Option D *</label>' +\n");
      out.write("                                '<input type=\"text\" name=\"optionD_' + num + '\" class=\"optionD-input\" required value=\"' + q.optionD + '\" placeholder=\"Option D\">' +\n");
      out.write("                            '</div>' +\n");
      out.write("                        '</div>' +\n");
      out.write("                        '<div class=\"form-row\">' +\n");
      out.write("                            '<div class=\"form-group\">' +\n");
      out.write("                                '<label>Reponse correcte *</label>' +\n");
      out.write("                                '<select name=\"correctAnswer_' + num + '\" class=\"correctAnswer-input\" required>' +\n");
      out.write("                                    '<option value=\"\">-- Selectionnez --</option>' +\n");
      out.write("                                    '<option value=\"a\" ' + selectedA + '>Option A</option>' +\n");
      out.write("                                    '<option value=\"b\" ' + selectedB + '>Option B</option>' +\n");
      out.write("                                    '<option value=\"c\" ' + selectedC + '>Option C</option>' +\n");
      out.write("                                    '<option value=\"d\" ' + selectedD + '>Option D</option>' +\n");
      out.write("                                '</select>' +\n");
      out.write("                            '</div>' +\n");
      out.write("                            '<div class=\"form-group\">' +\n");
      out.write("                                '<label>Points</label>' +\n");
      out.write("                                '<input type=\"number\" name=\"points_' + num + '\" class=\"points-input\" value=\"' + q.points + '\" min=\"1\" max=\"10\">' +\n");
      out.write("                            '</div>' +\n");
      out.write("                        '</div>';\n");
      out.write("                    \n");
      out.write("                    container.appendChild(questionDiv);\n");
      out.write("                    editQuestionCount++;\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.getElementById('editOfferModal').style.display = 'block';\n");
      out.write("            \n");
      out.write("            // Capture original form data for change detection\n");
      out.write("            setTimeout(captureOriginalFormData, 100);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function closeEditModal() {\n");
      out.write("            document.getElementById('editOfferModal').style.display = 'none';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function confirmDeleteById(id) {\n");
      out.write("            var offer = offerData[id];\n");
      out.write("            if (!offer) {\n");
      out.write("                alert('Erreur: Offre introuvable');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.getElementById('deleteOffreId').value = id;\n");
      out.write("            document.getElementById('deleteMessage').textContent = \n");
      out.write("                'Êtes-vous sûr de vouloir supprimer l\\'offre \"' + offer.titre + '\" ? Cette action est irréversible.';\n");
      out.write("            document.getElementById('deleteModal').style.display = 'block';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function closeDeleteModal() {\n");
      out.write("            document.getElementById('deleteModal').style.display = 'none';\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        window.onclick = function(event) {\n");
      out.write("            var offerModal = document.getElementById('offerModal');\n");
      out.write("            var editModal = document.getElementById('editOfferModal');\n");
      out.write("            var deleteModal = document.getElementById('deleteModal');\n");
      out.write("            const quizModal = document.getElementById('quizModal');\n");
      out.write("            \n");
      out.write("            if (event.target === offerModal) {\n");
      out.write("                closeOfferModal();\n");
      out.write("            }\n");
      out.write("            if (event.target === editModal) {\n");
      out.write("                closeEditModal();\n");
      out.write("            }\n");
      out.write("            if (event.target === deleteModal) {\n");
      out.write("                closeDeleteModal();\n");
      out.write("            }\n");
      out.write("            if (event.target === quizModal) {\n");
      out.write("                closeQuizModal();\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
