/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:51:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class error404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(jakarta.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Erreur 404 - Page non trouvée</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        .error-container {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 20px;\n");
      out.write("            background: linear-gradient(135deg, #f5f7fa 0%, #e9ecef 100%);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-card {\n");
      out.write("            max-width: 600px;\n");
      out.write("            width: 100%;\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("            padding: 60px 40px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-code {\n");
      out.write("            font-size: 120px;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--color-primary, #2563eb);\n");
      out.write("            line-height: 1;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-title {\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--color-text-main, #1f2937);\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-message {\n");
      out.write("            font-size: 16px;\n");
      out.write("            color: var(--color-text-muted, #6b7280);\n");
      out.write("            line-height: 1.6;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-actions {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("            justify-content: center;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-btn {\n");
      out.write("            padding: 12px 30px;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 15px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("            display: inline-block;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-btn-primary {\n");
      out.write("            background: var(--color-primary, #2563eb);\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-btn-primary:hover {\n");
      out.write("            background: var(--color-primary-hover, #1d4ed8);\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 4px 12px rgba(37, 99, 235, 0.3);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-btn-secondary {\n");
      out.write("            background: var(--color-bg-surface, #f3f4f6);\n");
      out.write("            color: var(--color-text-main, #1f2937);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-btn-secondary:hover {\n");
      out.write("            background: var(--color-bg-elevated, #e5e7eb);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .error-icon {\n");
      out.write("            font-size: 80px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            opacity: 0.8;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"error-container\">\n");
      out.write("        <div class=\"error-card\">\n");
      out.write("            <div class=\"error-code\">404</div>\n");
      out.write("            <h1 class=\"error-title\">Page non trouvée</h1>\n");
      out.write("            <p class=\"error-message\">\n");
      out.write("                Désolé, la page que vous recherchez n'existe pas ou a été déplacée.\n");
      out.write("                Veuillez vérifier l'URL ou retourner à l'accueil.\n");
      out.write("            </p>\n");
      out.write("            <div class=\"error-actions\">\n");
      out.write("                <a href=\"javascript:history.back()\" class=\"error-btn error-btn-secondary\">\n");
      out.write("                    ← Retour\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/login\" class=\"error-btn error-btn-primary\">\n");
      out.write("                    Login\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
