/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:50:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Connexion - StageConnect</title>\n");
      out.write("    \n");
      out.write("    <!-- Favicons -->\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"");
      out.print( request.getContextPath() );
      out.write("/android-chrome-192x192.png\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"auth-layout\">\n");
      out.write("        <!-- Left Side: Form -->\n");
      out.write("        <div class=\"auth-form-side\">\n");
      out.write("            <div class=\"auth-container\">\n");
      out.write("                <!-- Logo for Mobile Only -->\n");
      out.write("                <div class=\"auth-logo-mobile\">\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/logo-mobile.png\" alt=\"StageConnect Logo\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"auth-card\">\n");
      out.write("            <div class=\"auth-header\">\n");
      out.write("                <h1>StageConnect</h1>\n");
      out.write("                <p>Connectez-vous a votre compte</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    ");
      out.print( request.getAttribute("error") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            ");
 if (session.getAttribute("success") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-success\">\n");
      out.write("                    ");
      out.print( session.getAttribute("success") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("                ");
 session.removeAttribute("success"); 
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <div class=\"tab-buttons\">\n");
      out.write("                <button class=\"tab-btn active\" onclick=\"switchTab('student')\">Apprenant</button>\n");
      out.write("                <button class=\"tab-btn\" onclick=\"switchTab('entreprise')\">Entreprise</button>\n");
      out.write("                <button class=\"tab-btn\" onclick=\"switchTab('admin')\">Administration de l'Institut</button>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <form action=\"login\" method=\"post\" class=\"auth-form\">\n");
      out.write("                <input type=\"hidden\" name=\"userType\" id=\"userType\" value=\"student\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"identifier\" id=\"identifierLabel\">Identifiant ONEFD</label>\n");
      out.write("                    <input type=\"text\" id=\"identifier\" name=\"identifier\" required \n");
      out.write("                           placeholder=\"YYYY/XXX/XXXX\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"password\">Mot de passe</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" required\n");
      out.write("                           placeholder=\"Entrez votre mot de passe\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-block\">\n");
      out.write("                    Se connecter\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            <div class=\"auth-footer\" id=\"studentFooter\">\n");
      out.write("                <p>Pas encore de compte ? <a href=\"register?type=student\">S'inscrire</a></p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"auth-footer\" id=\"entrepriseFooter\" style=\"display: none;\">\n");
      out.write("                <p>Pas encore de compte ? <a href=\"register?type=entreprise\">S'inscrire</a></p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"auth-footer\" id=\"adminFooter\" style=\"display: none;\">\n");
      out.write("                <p class=\"text-muted\">Acces reserve aux administrateurs</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Right Side: Branding Image -->\n");
      out.write("        <div class=\"auth-image-side\">\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/auth-side.png\" alt=\"StageConnect\" class=\"auth-side-image\">\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function switchTab(type) {\n");
      out.write("            const tabs = document.querySelectorAll('.tab-btn');\n");
      out.write("            tabs.forEach(tab => tab.classList.remove('active'));\n");
      out.write("            event.target.classList.add('active');\n");
      out.write("            \n");
      out.write("            document.getElementById('userType').value = type;\n");
      out.write("            \n");
      out.write("            const identifierInput = document.getElementById('identifier');\n");
      out.write("            const identifierLabel = document.getElementById('identifierLabel');\n");
      out.write("            \n");
      out.write("            // Hide all footers\n");
      out.write("            document.getElementById('studentFooter').style.display = 'none';\n");
      out.write("            document.getElementById('entrepriseFooter').style.display = 'none';\n");
      out.write("            document.getElementById('adminFooter').style.display = 'none';\n");
      out.write("            \n");
      out.write("            if (type === 'admin') {\n");
      out.write("                document.getElementById('adminFooter').style.display = 'block';\n");
      out.write("                identifierLabel.textContent = \"Nom d'utilisateur\";\n");
      out.write("                identifierInput.placeholder = \"Nom d'utilisateur\";\n");
      out.write("                identifierInput.type = \"text\";\n");
      out.write("            } else if (type === 'entreprise') {\n");
      out.write("                document.getElementById('entrepriseFooter').style.display = 'block';\n");
      out.write("                identifierLabel.textContent = \"Email\";\n");
      out.write("                identifierInput.placeholder = \"email@entreprise.com\";\n");
      out.write("                identifierInput.type = \"email\";\n");
      out.write("            } else {\n");
      out.write("                document.getElementById('studentFooter').style.display = 'block';\n");
      out.write("                identifierLabel.textContent = \"Identifiant ONEFD\";\n");
      out.write("                identifierInput.placeholder = \"YYYY/XXX/XXXX (ex: 2024/123/4567)\";\n");
      out.write("                identifierInput.type = \"text\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
