/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:59:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.stages.model.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class offres_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.stages.model");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("login");
        return;
    }
    
    List<OffreStage> offres = (List<OffreStage>) request.getAttribute("offres");
    List<String> specialites = (List<String>) request.getAttribute("specialites");
    List<String> zones = (List<String>) request.getAttribute("zones");
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Offres de Stage - StageConnect</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/navbar.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>Offres de Stage</h1>\n");
      out.write("            <p>Trouvez le stage qui vous correspond</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");
 if (session.getAttribute("success") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert alert-success\">\n");
      out.write("                ");
      out.print( session.getAttribute("success") );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            ");
 session.removeAttribute("success"); 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        ");
 if (session.getAttribute("error") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert alert-error\">\n");
      out.write("                ");
      out.print( session.getAttribute("error") );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            ");
 session.removeAttribute("error"); 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- Filters -->\n");
      out.write("        <div class=\"card filter-card\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("                <form action=\"offres\" method=\"get\" class=\"filter-form\">\n");
      out.write("                    <div class=\"filter-row\">\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"specialite\">Spécialité</label>\n");
      out.write("                            <select id=\"specialite\" name=\"specialite\" onchange=\"this.form.submit()\">\n");
      out.write("                                <option value=\"\">Toutes les spécialités</option>\n");
      out.write("                                ");
 for (String spec : specialites) { 
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print( spec );
      out.write("\" \n");
      out.write("                                        ");
      out.print( spec.equals(request.getAttribute("selectedSpecialite")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                        ");
      out.print( spec );
      out.write("\n");
      out.write("                                    </option>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"zone\">Zone</label>\n");
      out.write("                            <select id=\"zone\" name=\"zone\" onchange=\"this.form.submit()\">\n");
      out.write("                                <option value=\"\">Toutes les zones</option>\n");
      out.write("                                ");
 for (String z : zones) { 
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print( z );
      out.write("\" \n");
      out.write("                                        ");
      out.print( z.equals(request.getAttribute("selectedZone")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                        ");
      out.print( z );
      out.write("\n");
      out.write("                                    </option>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <label for=\"type\">Type</label>\n");
      out.write("                            <select id=\"type\" name=\"type\" onchange=\"this.form.submit()\">\n");
      out.write("                                <option value=\"\">Tous les types</option>\n");
      out.write("                                <option value=\"Présentiel\" \n");
      out.write("                                    ");
      out.print( "Présentiel".equals(request.getAttribute("selectedType")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                    Présentiel\n");
      out.write("                                </option>\n");
      out.write("                                <option value=\"Apprentissage\" \n");
      out.write("                                    ");
      out.print( "Apprentissage".equals(request.getAttribute("selectedType")) ? "selected" : "" );
      out.write(">\n");
      out.write("                                    Apprentissage\n");
      out.write("                                </option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                            <a href=\"offres\" class=\"btn btn-secondary\">Réinitialiser</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Offers Grid -->\n");
      out.write("        <div class=\"offers-grid\">\n");
      out.write("            ");
 if (offres != null && !offres.isEmpty()) { 
      out.write("\n");
      out.write("                ");
 for (OffreStage offre : offres) { 
      out.write("\n");
      out.write("                    <div class=\"offer-card\">\n");
      out.write("                        <div class=\"offer-header\">\n");
      out.write("                            <h3>");
      out.print( offre.getTitre() );
      out.write("</h3>\n");
      out.write("                            <span class=\"badge badge-");
      out.print( offre.getTypeStage().equals("Apprentissage") ? "primary" : "secondary" );
      out.write("\">\n");
      out.write("                                ");
      out.print( offre.getTypeStage() );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"offer-entreprise\">\n");
      out.write("                            <strong> ");
      out.print( offre.getEntrepriseName() );
      out.write("</strong>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"offer-details\">\n");
      out.write("                            <div class=\"detail-item\">\n");
      out.write("                                <span>");
      out.print( offre.getSpecialite() );
      out.write("</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"detail-item\">\n");
      out.write("                                <span>");
      out.print( offre.getZoneGeographique() );
      out.write("</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"detail-item\">\n");
      out.write("                                <span>");
      out.print( offre.getDureeMois() );
      out.write(" mois</span>\n");
      out.write("                            </div>\n");
      out.write("                            ");
 if (offre.getRemuneration() != null && !offre.getRemuneration().isEmpty()) { 
      out.write("\n");
      out.write("                                <div class=\"detail-item\">\n");
      out.write("                                    <span>");
      out.print( offre.getRemuneration() );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                            ");
 if (offre.hasQuiz()) { 
      out.write("\n");
      out.write("                                <div class=\"detail-item\">\n");
      out.write("                                    <span class=\"badge badge-warning\">Quiz Requis</span>\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        <div class=\"offer-description\">\n");
      out.write("                            <p>");
      out.print( offre.getDescription().length() > 150 ? 
                                    offre.getDescription().substring(0, 150) + "..." : 
                                    offre.getDescription() );
      out.write("</p>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        ");
 if (offre.getCompetencesRequises() != null && !offre.getCompetencesRequises().isEmpty()) { 
      out.write("\n");
      out.write("                            <div class=\"offer-skills\">\n");
      out.write("                                <strong>Compétences :</strong> ");
      out.print( offre.getCompetencesRequises() );
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        \n");
      out.write("                        <div class=\"offer-actions\">\n");
      out.write("                            <a href=\"candidature?action=apply&offreId=");
      out.print( offre.getId() );
      out.write("\" class=\"btn btn-primary\">\n");
      out.write("                                Postuler\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"no-results\">\n");
      out.write("                    <p>Aucune offre de stage ne correspond à vos critères.</p>\n");
      out.write("                    <a href=\"offres\" class=\"btn btn-primary\">Voir toutes les offres</a>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script src=\"js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
