/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-02-23 11:55:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String userType = request.getParameter("type");
    if (userType == null || userType.isEmpty()) {
        userType = "student";
    }
    boolean isEntreprise = "entreprise".equals(userType);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Inscription - StageConnect</title>\n");
      out.write("    \n");
      out.write("    <!-- Favicons -->\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-16x16.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon-32x32.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print( request.getContextPath() );
      out.write("/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"");
      out.print( request.getContextPath() );
      out.write("/android-chrome-192x192.png\">\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"auth-layout\">\n");
      out.write("        <!-- Left Side: Form -->\n");
      out.write("        <div class=\"auth-form-side\">\n");
      out.write("            <div class=\"auth-container\">\n");
      out.write("                <!-- Logo for Mobile Only -->\n");
      out.write("                <div class=\"auth-logo-mobile\">\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/logo-mobile.png\" alt=\"StageConnect Logo\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"auth-card\">\n");
      out.write("            <div class=\"auth-header\">\n");
      out.write("                <h1>Creer un compte</h1>\n");
      out.write("                <p>Inscrivez-vous pour acceder aux offres de stage</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    ");
      out.print( request.getAttribute("error") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <div class=\"tab-buttons\">\n");
      out.write("                <button class=\"tab-btn ");
      out.print( !isEntreprise ? "active" : "" );
      out.write("\" onclick=\"switchRegisterTab('student')\">Étudiant</button>\n");
      out.write("                <button class=\"tab-btn ");
      out.print( isEntreprise ? "active" : "" );
      out.write("\" onclick=\"switchRegisterTab('entreprise')\">Entreprise</button>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Student Registration Form -->\n");
      out.write("            <form action=\"register\" method=\"post\" class=\"auth-form\" id=\"studentForm\" style=\"");
      out.print( isEntreprise ? "display: none;" : "" );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"userType\" value=\"student\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"onefdId\">Identifiant ONEFD *</label>\n");
      out.write("                    <input type=\"text\" id=\"onefdId\" name=\"onefdId\" required\n");
      out.write("                           pattern=\"\\d{4}/\\d{3}/\\d{4}\"\n");
      out.write("                           placeholder=\"YYYY/XXX/XXXX (ex: 2024/123/4567)\"\n");
      out.write("                           title=\"Format: YYYY/XXX/XXXX\"\n");
      out.write("                           value=\"");
      out.print( request.getParameter("onefdId") != null ? request.getParameter("onefdId") : "" );
      out.write("\">\n");
      out.write("                    <small class=\"form-text\">Utilisez l'identifiant fourni par ONEFD</small>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"nom\">Nom *</label>\n");
      out.write("                        <input type=\"text\" id=\"nom\" name=\"nom\" required\n");
      out.write("                               value=\"");
      out.print( request.getParameter("nom") != null ? request.getParameter("nom") : "" );
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"prenom\">Prénom *</label>\n");
      out.write("                        <input type=\"text\" id=\"prenom\" name=\"prenom\" required\n");
      out.write("                               value=\"");
      out.print( request.getParameter("prenom") != null ? request.getParameter("prenom") : "" );
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"password\">Mot de passe *</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" required\n");
      out.write("                           placeholder=\"Minimum 6 caractères\" minlength=\"6\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"confirmPassword\">Confirmer le mot de passe *</label>\n");
      out.write("                    <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" required\n");
      out.write("                           placeholder=\"Confirmez votre mot de passe\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-block\">\n");
      out.write("                    S'inscrire\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            <!-- Enterprise Registration Form -->\n");
      out.write("            <form action=\"register\" method=\"post\" class=\"auth-form\" id=\"entrepriseForm\" style=\"");
      out.print( !isEntreprise ? "display: none;" : "" );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"userType\" value=\"entreprise\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"nomEntreprise\">Nom de l'entreprise *</label>\n");
      out.write("                    <input type=\"text\" id=\"nomEntreprise\" name=\"nomEntreprise\" required\n");
      out.write("                           value=\"");
      out.print( request.getParameter("nomEntreprise") != null ? request.getParameter("nomEntreprise") : "" );
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"emailEntreprise\">Email *</label>\n");
      out.write("                    <input type=\"email\" id=\"emailEntreprise\" name=\"email\" required\n");
      out.write("                           placeholder=\"contact@entreprise.com\"\n");
      out.write("                           value=\"");
      out.print( request.getParameter("email") != null ? request.getParameter("email") : "" );
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"passwordEntreprise\">Mot de passe *</label>\n");
      out.write("                    <input type=\"password\" id=\"passwordEntreprise\" name=\"password\" required\n");
      out.write("                           placeholder=\"Minimum 6 caractères\" minlength=\"6\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"confirmPasswordEntreprise\">Confirmer le mot de passe *</label>\n");
      out.write("                    <input type=\"password\" id=\"confirmPasswordEntreprise\" name=\"confirmPassword\" required\n");
      out.write("                           placeholder=\"Confirmez votre mot de passe\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-block\">\n");
      out.write("                    S'inscrire\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            <div class=\"auth-footer\">\n");
      out.write("                <p>Déjà un compte ? <a href=\"login\">Se connecter</a></p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Right Side: Branding Image -->\n");
      out.write("        <div class=\"auth-image-side\">\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/auth-side.png\" alt=\"StageConnect\" class=\"auth-side-image\">\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function switchRegisterTab(type) {\n");
      out.write("            const tabs = document.querySelectorAll('.tab-btn');\n");
      out.write("            tabs.forEach(tab => tab.classList.remove('active'));\n");
      out.write("            event.target.classList.add('active');\n");
      out.write("            \n");
      out.write("            const studentForm = document.getElementById('studentForm');\n");
      out.write("            const entrepriseForm = document.getElementById('entrepriseForm');\n");
      out.write("            \n");
      out.write("            if (type === 'entreprise') {\n");
      out.write("                studentForm.style.display = 'none';\n");
      out.write("                entrepriseForm.style.display = 'block';\n");
      out.write("            } else {\n");
      out.write("                studentForm.style.display = 'block';\n");
      out.write("                entrepriseForm.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
